# k8s/values/astronomy-shop.yaml
# Compatible with opentelemetry-demo chart v0.31.0+

default:
  env:
    - name: OTEL_SERVICE_NAME
      value: "astro-demo-app"
    - name: OTEL_COLLECTOR_NAME
      value: "openobserve-collector-gateway-collector.openobserve-collector-system.svc.cluster.local"
    # Points to the Gateway Service created by the single 'openobserve-collector' release
    # - name: OTEL_EXPORTER_OTLP_ENDPOINT
    #   value: "http://openobserve-collector-gateway.openobserve-collector-system.svc.cluster.local:4317"
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    # - name: OTEL_EXPORTER_OTLP_PROTOCOL
    #   value: "http/protobuf"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=astro-demo-app,space=devteam-1,deployment.environment=production"
    - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
      value: cumulative
# components:
#   loadgenerator:
#     enabled: true
#     # env:
#     #   # - name: OTEL_EXPORTER_OTLP_ENDPOINT
#     #   #   value: "http://openobserve-collector-gateway.openobserve-collector-system.svc.cluster.local:4317"
#     #   - name: OTEL_COLLECTOR_NAME
#     #     value: "openobserve-collector-gateway-collector"
#     #   - name: OTEL_EXPORTER_OTLP_INSECURE
#     #     value: "true"
#     #   - name: OTEL_RESOURCE_ATTRIBUTES
#     #     value: "service.name=astro-demo-app,space=devteam-1,deployment.environment=production"
#     #   - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
#     #     value: cumulative
#   frontendProxy:
#     service:
#       type: ClusterIP
#       port: 8080

# Disable Internal Demo Stack (We use OpenObserve instead)
opentelemetry-collector:
  enabled: false
jaeger:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
opensearch:
  enabled: false