# k8s/values/astronomy-shop.yaml
# Compatible with opentelemetry-demo chart v0.31.0+

default:
  env:
    - name: OTEL_SERVICE_NAME
      value: "astro-demo-app"
    - name: OTEL_COLLECTOR_NAME
      value: "openobserve-collector-gateway-collector.openobserve-collector-system.svc.cluster.local"
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=astro-demo-app,space=devteam-1,deployment.environment=production"
    - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
      value: cumulative

# Disable Internal Demo Stack (We use OpenObserve instead)
opentelemetry-collector:
  enabled: false
jaeger:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
opensearch:
  enabled: false